participants:
  - el_type: geth
    cl_type: lighthouse
network_params:
  network_type: "ethereum"
plugins: [] # Currently supports Uniswap and Chainlink. Note: both require forked network (reth client)
env: dev