participants:
  - el_type: reth
    el_image: tiljordan/reth-forking:1.0.0
    el_extra_env_vars:
      FORKING_RPC_URL: <FORKING_RPC_URL>
      FORKING_BLOCK_HEIGHT: "latest"
    cl_type: lighthouse
network_params:
  additional_preloaded_contracts: {}
additional_services:
  - faucet
plugins:
  uniswap: {}
  chainlink:
    network_type: "ethereum"
  vrf:
    network_type: "ethereum"
    vrf_type: "vrfv2plus"
    private_key: "0x0000000000000000000000000000000000000000000000000000000000000000"
    chain_id: "1"
    link_address: "0x0000000000000000000000000000000000000000"
    link_native_token_feed_address: "0x0000000000000000000000000000000000000000"
env: dev

optimism_params:
  chains:
    - participants:
      - el_type: op-geth
        cl_type: op-node
        count: 1
      network_params:
        network: "kurtosis"
        network_id: "2151908"
        name: "op-kurtosis"
      additional_services: []
  op_contract_deployer_params:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-deployer:v0.0.12
    l1_artifacts_locator: https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-fffcbb0ebf7f83311791534a41e65ef90df47797f9ca8f86941452f597f7128c.tar.gz
    l2_artifacts_locator: https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-fffcbb0ebf7f83311791534a41e65ef90df47797f9ca8f86941452f597f7128c.tar.gz
  global_log_level: "info"
  global_node_selectors: {}
  global_tolerations: []
  persistent: false

external_l1_network_params:
  rpc_kind: "standard"
  el_rpc_url: ""
  cl_rpc_url: ""
  el_ws_url: ""
  network_id: ""
  priv_key: ""